; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32_4mb_debug
lib_dir = lib

[common]
framework           = arduino

lib_ldf_mode        = deep+
lib_deps            =
    https://github.com/Erriez/ErriezDS3231
    https://github.com/2dom/PxMatrix.git
    https://github.com/golyakoff/TetrisAnimation.git
lib_ignore          =

build_unflags       = -Werror=reorder
build_flags         = -O2
                      -D CONFIG_ARDUINO_ISR_IRAM=1
                      -D CONFIG_BT_ENABLED=1

monitor_speed       = 115200
monitor_filters     = --quiet
                      --echo
                      --eol
                        LF
                      --filter
                        time

upload_speed        = 921600
upload_protocol     = esptool
upload_port         = COM3

[env:esp32_4mb]
framework           = ${common.framework}
platform            = https://github.com/platformio/platform-espressif32.git
board               = esp32doit-devkit-v1

board_build.f_cpu    = 240000000L
board_build.f_flash  = 80000000L
board_build.flash_mode    = dio
board_build.partitions    = ./partitions/4MB.csv
board_upload.flash_size   = 4MB
board_upload.maximum_size = 1966080 ; partition size 1E0000 = 1920 KB

build_unflags       = ${common.build_unflags}
build_flags         = ${common.build_flags}
                      -DCORE_DEBUG_LEVEL=0

monitor_speed       = ${common.monitor_speed}
monitor_filters     = esp32_exception_decoder
                      ${common.monitor_filters}

lib_deps            = ${common.lib_deps}
lib_ignore          = ${common.lib_ignore}
lib_ldf_mode        = ${common.lib_ldf_mode}

upload_protocol     = ${common.upload_protocol}
upload_speed        = ${common.upload_speed}
upload_port         = ${common.upload_port}

[env:esp32_4mb_debug]
extends             = env:esp32_4mb
build_type          = debug
build_flags         = -Og
                      -g
                      -DDEBUG
                      -DPLATFORMIO_DEBUG
                      -DCORE_DEBUG_LEVEL=0

[env:esp32_16mb]
framework           = ${common.framework}
platform            = https://github.com/platformio/platform-espressif32.git
board               = esp32doit-devkit-v1

board_build.f_cpu    = 240000000L
board_build.f_flash  = 80000000L
board_build.flash_mode    = dio
board_build.partitions    = ./partitions/16MB.csv
board_upload.flash_size   = 16MB
board_upload.maximum_size = 8257536 ; partition size 7E0000 = 8064 KB

build_unflags       = ${common.build_unflags}
build_flags         = ${common.build_flags}
                      -DCORE_DEBUG_LEVEL=0

monitor_speed       = ${common.monitor_speed}
monitor_filters     = esp32_exception_decoder
                      ${common.monitor_filters}

lib_deps            = ${common.lib_deps}
lib_ignore          = ${common.lib_ignore}
lib_ldf_mode        = ${common.lib_ldf_mode}

upload_protocol     = ${common.upload_protocol}
upload_speed        = ${common.upload_speed}
upload_port         = ${common.upload_port}

[env:esp32_16mb_debug]
extends             = env:esp32_16MB
build_type          = debug
build_flags         = -Og
                      -g
                      -DDEBUG
                      -DPLATFORMIO_DEBUG
                      -DCORE_DEBUG_LEVEL=0