; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32
lib_dir = lib

[common]
framework           = arduino

lib_ldf_mode        = deep+
lib_deps            =
    ;https://github.com/Erriez/ErriezDS3231
    ;https://github.com/2dom/PxMatrix.git
    ;https://github.com/toblum/TetrisAnimation.git
lib_ignore          =

build_unflags       = -Werror=reorder
build_flags         = -O2

monitor_speed       = 115200
monitor_filters     = --quiet
                      --echo
                      --eol
                        LF
                      --filter
                        time

upload_speed        = 921600

[env:esp32]
framework           = ${common.framework}
;platform            = espressif32
platform            = https://github.com/platformio/platform-espressif32.git
board               = esp32doit-devkit-v1

build_unflags       = ${common.build_unflags}
build_flags         = ${common.build_flags}
                      -DCORE_DEBUG_LEVEL=0

monitor_speed       = ${common.monitor_speed}
monitor_filters     = esp32_exception_decoder
                      ${common.monitor_filters}
upload_speed        = ${common.upload_speed}

lib_deps            = ${common.lib_deps}
lib_ignore          = ${common.lib_ignore}
lib_ldf_mode        = ${common.lib_ldf_mode}

upload_port         = COM7